# Generated by Django 5.2.4 on 2025-08-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=255)),
                ("title", models.TextField()),
                ("link", models.URLField()),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
