# Generated by Django 5.2.4 on 2025-08-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchresult",
            name="snippet",
            field=models.TextField(blank=True),
        ),
    ]
